import type {
  Assignment,
  AssignmentWord,
  Class,
  ClassMembership,
  Reward,
  StudentProfile,
  StudentSupportProfile,
  TeacherProfile,
  User,
} from "@/lib/types";
import { SEED_IDS } from "@/lib/seed/seed-ids";
import { seedTimestamps } from "@/lib/seed/helpers";
import { SEED_VOCABULARY, SEED_WORD_IDS } from "@/lib/seed/vocabulary";

const ts = seedTimestamps();

export const SEED_USERS: User[] = [
  {
    id: SEED_IDS.users.teacherRivera,
    email: "m.rivera@demo.school",
    displayName: "Ms. Rivera",
    role: "teacher",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.adminChen,
    email: "d.chen@demo.school",
    displayName: "Dr. Chen",
    role: "admin",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.sofiaMartinez,
    email: "sofia.martinez@demo.school",
    displayName: "Sofia Martinez",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.marcusJohnson,
    email: "marcus.johnson@demo.school",
    displayName: "Marcus Johnson",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.aishaPatel,
    email: "aisha.patel@demo.school",
    displayName: "Aisha Patel",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.liamObrien,
    email: "liam.obrien@demo.school",
    displayName: "Liam O'Brien",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.emmaChen,
    email: "emma.chen@demo.school",
    displayName: "Emma Chen",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.noahWilliams,
    email: "noah.williams@demo.school",
    displayName: "Noah Williams",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.zaraAhmed,
    email: "zara.ahmed@demo.school",
    displayName: "Zara Ahmed",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.ethanBrooks,
    email: "ethan.brooks@demo.school",
    displayName: "Ethan Brooks",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.oliviaNguyen,
    email: "olivia.nguyen@demo.school",
    displayName: "Olivia Nguyen",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.jaydenTaylor,
    email: "jayden.taylor@demo.school",
    displayName: "Jayden Taylor",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.miaRodriguez,
    email: "mia.rodriguez@demo.school",
    displayName: "Mia Rodriguez",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.calebWashington,
    email: "caleb.washington@demo.school",
    displayName: "Caleb Washington",
    role: "student",
    isActive: true,
    ...ts,
  },
  {
    id: SEED_IDS.users.students.graceKim,
    email: "grace.kim@demo.school",
    displayName: "Grace Kim",
    role: "student",
    isActive: true,
    ...ts,
  },
];

export const SEED_TEACHER_PROFILES: TeacherProfile[] = [
  {
    id: "seed-profile-teacher-rivera",
    userId: SEED_IDS.users.teacherRivera,
    schoolName: "Lakeside Elementary",
    ...ts,
  },
];

export const SEED_STUDENT_PROFILES: StudentProfile[] = [
  {
    id: "seed-student-profile-sofia",
    userId: SEED_IDS.users.students.sofiaMartinez,
    gradeLevel: 5,
    defaultSupportLevel: 2,
    supportProfileId: "seed-support-sofia",
    journeyProgress: 42,
    ...ts,
  },
  {
    id: "seed-student-profile-marcus",
    userId: SEED_IDS.users.students.marcusJohnson,
    gradeLevel: 5,
    defaultSupportLevel: 1,
    supportProfileId: "seed-support-marcus",
    journeyProgress: 28,
    ...ts,
  },
  {
    id: "seed-student-profile-aisha",
    userId: SEED_IDS.users.students.aishaPatel,
    gradeLevel: 5,
    defaultSupportLevel: 3,
    supportProfileId: "seed-support-aisha",
    journeyProgress: 55,
    ...ts,
  },
  {
    id: "seed-student-profile-liam",
    userId: SEED_IDS.users.students.liamObrien,
    gradeLevel: 5,
    defaultSupportLevel: 2,
    supportProfileId: "seed-support-liam",
    journeyProgress: 36,
    ...ts,
  },
  {
    id: "seed-student-profile-emma",
    userId: SEED_IDS.users.students.emmaChen,
    gradeLevel: 5,
    defaultSupportLevel: 3,
    supportProfileId: "seed-support-emma",
    journeyProgress: 78,
    ...ts,
  },
  {
    id: "seed-student-profile-noah",
    userId: SEED_IDS.users.students.noahWilliams,
    gradeLevel: 5,
    defaultSupportLevel: 1,
    supportProfileId: "seed-support-noah",
    journeyProgress: 19,
    ...ts,
  },
  {
    id: "seed-student-profile-zara",
    userId: SEED_IDS.users.students.zaraAhmed,
    gradeLevel: 5,
    defaultSupportLevel: 2,
    supportProfileId: "seed-support-zara",
    journeyProgress: 47,
    ...ts,
  },
  {
    id: "seed-student-profile-ethan",
    userId: SEED_IDS.users.students.ethanBrooks,
    gradeLevel: 5,
    defaultSupportLevel: 2,
    supportProfileId: "seed-support-ethan",
    journeyProgress: 33,
    ...ts,
  },
  {
    id: "seed-student-profile-olivia",
    userId: SEED_IDS.users.students.oliviaNguyen,
    gradeLevel: 5,
    defaultSupportLevel: 4,
    supportProfileId: "seed-support-olivia",
    journeyProgress: 86,
    ...ts,
  },
  {
    id: "seed-student-profile-jayden",
    userId: SEED_IDS.users.students.jaydenTaylor,
    gradeLevel: 5,
    defaultSupportLevel: 1,
    supportProfileId: "seed-support-jayden",
    journeyProgress: 24,
    ...ts,
  },
  {
    id: "seed-student-profile-mia",
    userId: SEED_IDS.users.students.miaRodriguez,
    gradeLevel: 5,
    defaultSupportLevel: 3,
    supportProfileId: "seed-support-mia",
    journeyProgress: 51,
    ...ts,
  },
  {
    id: "seed-student-profile-caleb",
    userId: SEED_IDS.users.students.calebWashington,
    gradeLevel: 5,
    defaultSupportLevel: 2,
    supportProfileId: "seed-support-caleb",
    journeyProgress: 12,
    ...ts,
  },
  {
    id: "seed-student-profile-grace",
    userId: SEED_IDS.users.students.graceKim,
    gradeLevel: 5,
    defaultSupportLevel: 3,
    supportProfileId: "seed-support-grace",
    journeyProgress: 64,
    ...ts,
  },
];

export const SEED_SUPPORT_PROFILES: StudentSupportProfile[] = [
  {
    id: "seed-support-sofia",
    studentId: SEED_IDS.users.students.sofiaMartinez,
    fontPreference: "default",
    textSize: "large",
    letterSpacing: "wide",
    lineSpacing: "relaxed",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: true,
    syllableHighlighting: true,
    morphemeHighlighting: false,
    numberOfDistractors: 3,
    wordBank: true,
    pictureSupport: true,
    extendedTime: true,
    bilingualGlossary: true,
    preferredGlossaryLanguage: "es",
    speechRecognitionAlternative: true,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-marcus",
    studentId: SEED_IDS.users.students.marcusJohnson,
    fontPreference: "opendyslexic",
    textSize: "extra_large",
    letterSpacing: "extra_wide",
    lineSpacing: "loose",
    reducedMotion: true,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: true,
    syllableHighlighting: true,
    morphemeHighlighting: true,
    numberOfDistractors: 2,
    wordBank: true,
    pictureSupport: true,
    extendedTime: true,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: true,
    inputPreference: "both",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-aisha",
    studentId: SEED_IDS.users.students.aishaPatel,
    fontPreference: "default",
    textSize: "medium",
    letterSpacing: "normal",
    lineSpacing: "normal",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: false,
    slowPlayback: false,
    syllableHighlighting: false,
    morphemeHighlighting: false,
    numberOfDistractors: 4,
    wordBank: false,
    pictureSupport: false,
    extendedTime: false,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: false,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-liam",
    studentId: SEED_IDS.users.students.liamObrien,
    fontPreference: "high_legibility_sans",
    textSize: "large",
    letterSpacing: "wide",
    lineSpacing: "relaxed",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: false,
    syllableHighlighting: true,
    morphemeHighlighting: false,
    numberOfDistractors: 3,
    wordBank: true,
    pictureSupport: true,
    extendedTime: true,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: true,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-emma",
    studentId: SEED_IDS.users.students.emmaChen,
    fontPreference: "default",
    textSize: "medium",
    letterSpacing: "normal",
    lineSpacing: "normal",
    reducedMotion: false,
    audioDirections: false,
    textToSpeech: false,
    slowPlayback: false,
    syllableHighlighting: false,
    morphemeHighlighting: true,
    numberOfDistractors: 4,
    wordBank: false,
    pictureSupport: false,
    extendedTime: false,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: false,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-noah",
    studentId: SEED_IDS.users.students.noahWilliams,
    fontPreference: "opendyslexic",
    textSize: "extra_large",
    letterSpacing: "extra_wide",
    lineSpacing: "loose",
    reducedMotion: true,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: true,
    syllableHighlighting: true,
    morphemeHighlighting: true,
    numberOfDistractors: 2,
    wordBank: true,
    pictureSupport: true,
    extendedTime: true,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: true,
    inputPreference: "handwriting",
    studentAdjustableDisplay: false,
    ...ts,
  },
  {
    id: "seed-support-zara",
    studentId: SEED_IDS.users.students.zaraAhmed,
    fontPreference: "default",
    textSize: "large",
    letterSpacing: "wide",
    lineSpacing: "relaxed",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: true,
    syllableHighlighting: true,
    morphemeHighlighting: false,
    numberOfDistractors: 3,
    wordBank: true,
    pictureSupport: true,
    extendedTime: true,
    bilingualGlossary: true,
    preferredGlossaryLanguage: "vi",
    speechRecognitionAlternative: true,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-ethan",
    studentId: SEED_IDS.users.students.ethanBrooks,
    fontPreference: "default",
    textSize: "medium",
    letterSpacing: "normal",
    lineSpacing: "normal",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: false,
    syllableHighlighting: true,
    morphemeHighlighting: false,
    numberOfDistractors: 3,
    wordBank: true,
    pictureSupport: false,
    extendedTime: false,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: true,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-olivia",
    studentId: SEED_IDS.users.students.oliviaNguyen,
    fontPreference: "default",
    textSize: "medium",
    letterSpacing: "normal",
    lineSpacing: "normal",
    reducedMotion: false,
    audioDirections: false,
    textToSpeech: false,
    slowPlayback: false,
    syllableHighlighting: false,
    morphemeHighlighting: false,
    numberOfDistractors: 4,
    wordBank: false,
    pictureSupport: false,
    extendedTime: false,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: false,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-jayden",
    studentId: SEED_IDS.users.students.jaydenTaylor,
    fontPreference: "opendyslexic",
    textSize: "large",
    letterSpacing: "extra_wide",
    lineSpacing: "relaxed",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: true,
    syllableHighlighting: true,
    morphemeHighlighting: true,
    numberOfDistractors: 2,
    wordBank: true,
    pictureSupport: true,
    extendedTime: true,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: true,
    inputPreference: "both",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-mia",
    studentId: SEED_IDS.users.students.miaRodriguez,
    fontPreference: "default",
    textSize: "medium",
    letterSpacing: "normal",
    lineSpacing: "normal",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: false,
    slowPlayback: false,
    syllableHighlighting: false,
    morphemeHighlighting: false,
    numberOfDistractors: 4,
    wordBank: false,
    pictureSupport: true,
    extendedTime: false,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: false,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-caleb",
    studentId: SEED_IDS.users.students.calebWashington,
    fontPreference: "default",
    textSize: "large",
    letterSpacing: "wide",
    lineSpacing: "relaxed",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: true,
    syllableHighlighting: true,
    morphemeHighlighting: false,
    numberOfDistractors: 3,
    wordBank: true,
    pictureSupport: true,
    extendedTime: true,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: true,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
  {
    id: "seed-support-grace",
    studentId: SEED_IDS.users.students.graceKim,
    fontPreference: "default",
    textSize: "medium",
    letterSpacing: "normal",
    lineSpacing: "normal",
    reducedMotion: false,
    audioDirections: true,
    textToSpeech: true,
    slowPlayback: false,
    syllableHighlighting: true,
    morphemeHighlighting: false,
    numberOfDistractors: 3,
    wordBank: false,
    pictureSupport: false,
    extendedTime: false,
    bilingualGlossary: false,
    preferredGlossaryLanguage: null,
    speechRecognitionAlternative: false,
    inputPreference: "typing",
    studentAdjustableDisplay: true,
    ...ts,
  },
];

export const SEED_CLASS: Class = {
  id: SEED_IDS.class.riveraPeriod3,
  name: "Period 3 — Grade 5 Science",
  teacherId: SEED_IDS.users.teacherRivera,
  gradeLevel: 5,
  defaultSupportLevel: 2,
  isActive: true,
  ...ts,
};

export const SEED_CLASS_MEMBERSHIPS: ClassMembership[] = [
  {
    id: "seed-membership-teacher",
    classId: SEED_IDS.class.riveraPeriod3,
    userId: SEED_IDS.users.teacherRivera,
    role: "teacher",
    joinedAt: ts.createdAt,
    ...ts,
  },
  ...Object.values(SEED_IDS.users.students).map((studentId, index) => ({
    id: `seed-membership-student-${index + 1}`,
    classId: SEED_IDS.class.riveraPeriod3,
    userId: studentId,
    role: "student" as const,
    joinedAt: ts.createdAt,
    ...ts,
  })),
];

export const SEED_ASSIGNMENTS: Assignment[] = [
  {
    id: SEED_IDS.assignment.waterCycleUnit,
    classId: SEED_IDS.class.riveraPeriod3,
    unitId: SEED_IDS.units.waterCycle,
    teacherId: SEED_IDS.users.teacherRivera,
    title: "Water Cycle Vocabulary",
    defaultSupportLevel: 2,
    dueDate: "2026-08-15T23:59:59.000Z",
    status: "active",
    ...ts,
  },
  {
    id: SEED_IDS.assignment.ecosystemsUnit,
    classId: SEED_IDS.class.riveraPeriod3,
    unitId: SEED_IDS.units.ecosystems,
    teacherId: SEED_IDS.users.teacherRivera,
    title: "Ecosystems Vocabulary",
    defaultSupportLevel: 2,
    dueDate: "2026-09-01T23:59:59.000Z",
    status: "active",
    ...ts,
  },
  {
    id: SEED_IDS.assignment.matterUnit,
    classId: SEED_IDS.class.riveraPeriod3,
    unitId: SEED_IDS.units.matter,
    teacherId: SEED_IDS.users.teacherRivera,
    title: "Matter Vocabulary",
    defaultSupportLevel: 2,
    dueDate: "2026-07-20T23:59:59.000Z",
    status: "active",
    ...ts,
  },
];

const waterCycleWordIds = SEED_VOCABULARY.filter((w) => w.unitId === SEED_IDS.units.waterCycle).map(
  (w) => w.id,
);
const ecosystemWordIds = SEED_VOCABULARY.filter((w) => w.unitId === SEED_IDS.units.ecosystems).map(
  (w) => w.id,
);
const matterWordIds = SEED_VOCABULARY.filter((w) => w.unitId === SEED_IDS.units.matter).map(
  (w) => w.id,
);

function assignmentWords(
  assignmentId: string,
  wordIds: string[],
): AssignmentWord[] {
  return wordIds.map((vocabularyWordId, index) => ({
    id: `seed-assignment-word-${assignmentId}-${index}`,
    assignmentId,
    vocabularyWordId,
    supportLevelOverride: null,
    sortOrder: index + 1,
    createdAt: ts.createdAt,
  }));
}

export const SEED_ASSIGNMENT_WORDS: AssignmentWord[] = [
  ...assignmentWords(SEED_IDS.assignment.waterCycleUnit, waterCycleWordIds),
  ...assignmentWords(SEED_IDS.assignment.ecosystemsUnit, ecosystemWordIds),
  ...assignmentWords(SEED_IDS.assignment.matterUnit, matterWordIds),
];

export const SEED_REWARDS: Reward[] = [
  {
    id: "seed-reward-lab-badge-1",
    slug: "first-hypothesis",
    title: "First Hypothesis",
    description: "Completed your first scientific investigation word.",
    category: "lab_badge",
    imageUrl: null,
    pointsRequired: 10,
    isActive: true,
    ...ts,
  },
  {
    id: "seed-reward-water-cycle",
    slug: "water-cycle-explorer",
    title: "Water Cycle Explorer",
    description: "Mastered three water cycle vocabulary words.",
    category: "wilderness_trail",
    imageUrl: null,
    pointsRequired: 30,
    isActive: true,
    ...ts,
  },
  {
    id: "seed-reward-ecosystem-garden",
    slug: "ecosystem-garden-seed",
    title: "Ecosystem Garden Seed",
    description: "Earned by connecting producers and consumers in vocabulary practice.",
    category: "garden_item",
    imageUrl: null,
    pointsRequired: 25,
    isActive: true,
    ...ts,
  },
];

export const DEMO_WORD_IDS = [
  SEED_WORD_IDS.evaporation,
  SEED_WORD_IDS.atom,
  SEED_WORD_IDS.force,
  SEED_WORD_IDS.ecosystem,
  SEED_WORD_IDS.hypothesis,
  SEED_WORD_IDS.condensation,
];
